### PR TITLE
Various fixes for 'stairs' and 'hud' mods

### LINKED ISSUE #89: Various in-game warnings
```
2017-07-22 21:56:55: WARNING[Main]: Undeclared global variable "mobs" accessed at
...ultiCraft/bin/../games/default/files/stairs/init.lua:288
2017-07-22 21:56:55: WARNING[Main]: Undeclared global variable "HUD_ENABLE_HUNGER"
accessed at ...ultiCraft/bin/../games/default/files/hud/builtin.lua:38
2017-07-22 21:57:02: WARNING[Server]: Assignment to undeclared global "list_name" inside
a function at ...aft/bin/../games/default/files/dungeon_loot/init.lua:97.
2017-07-22 21:57:02: WARNING[Server]: Assignment to undeclared global "list_name_string"
inside a function at ...aft/bin/../games/default/files/dungeon_loot/init.lua:98.
2017-07-22 21:57:02: WARNING[Server]: Assignment to undeclared global "lsf" inside a
function at ...aft/bin/../games/default/files/dungeon_loot/init.lua:100.
```
PR coming.

### PR DESCRIPTION
**Pull request by paramat**
Fix undeclared global variables in 'stairs' and 'hud' mods.

Stairs mod:
Add to 'depends.txt' to enable cheeseblock and wool slabs/stairs.
Improve detection of mobs mods.
Remove 'mobs:honey_block' slabs/stairs as the node does not exist.
//////////////

Tested.
Partly fixes #89 but the warnings for dungeon_loot mod are difficult to fix, i will contact the mod author about this.

### CODE REVIEW

File: games/default/files/hud/builtin.lua [hunk 1]
```diff
@@ -1,3 +1,4 @@
+HUD_ENABLE_HUNGER = false -- MC add line ************************************************
```
Comment (MoNTE48) [inline games/default/files/hud/builtin.lua]: @paramat Why is this necessary?
MultiCraft uses hunger

Comment (paramat) [inline games/default/files/hud/builtin.lua]: I will investigate this.

**Comment by paramat** [comment]
I tested the value of HUD_ENABLE_HUNGER with this code at line 36:
```
-- check if some settings are invalid
local enable_hunger = minetest.setting_getbool("hud_hunger_enable")
print("hud enable hunger" .. HUD_ENABLE_HUNGER)
if (enable_hunger == true or HUD_ENABLE_HUNGER == true) and not hud.show_hunger then
	hud.notify_hunger(5)
end
```
The result was:
```
ERROR[Main]: ...ultiCraft/bin/../games/default/files/hud/builtin.lua:38: attempt to
concatenate global 'HUD_ENABLE_HUNGER' (a nil value)
```
So `HUD_ENABLE_HUNGER` is 'nil' at line 38, which causes the warning in issue #89:
```
2017-07-22 21:56:55: WARNING[Main]: Undeclared global variable "HUD_ENABLE_HUNGER"
accessed at ...ultiCraft/bin/../games/default/files/hud/builtin.lua:38
```
Since `HUD_ENABLE_HUNGER` is nil,  `HUD_ENABLE_HUNGER == true` is false.
The code at line 36 ..
```
-- check if some settings are invalid
local enable_hunger = minetest.setting_getbool("hud_hunger_enable")
print("hud enable hunger" .. HUD_ENABLE_HUNGER)
if (enable_hunger == true or HUD_ENABLE_HUNGER == true) and not hud.show_hunger then
	hud.notify_hunger(5)
end
```
.. checks for old unused settings `hud_hunger_enable` and 'HUD_ENABLE_HUNGER`, both are 'nil' in MC. It also checks for the 'hunger' mod, and `hud.notify_hunger(5)` is a function that only prints a warning:
```
function hud.notify_hunger(delay, use)
	local txt_part = "enable"
	if use then
		txt_part = "use"
	end
	minetest.after(delay, function()
		minetest.chat_send_all("#Better HUD: You can't " .. txt_part .. " hunger without the \"hunger\" mod")
		minetest.chat_send_all("	Enable it or download it from \"https://github.com/BlockMen/hunger\"")
	end)
end
```

So, setting `HUD_ENABLE_HUNGER = false` changes nothing, you can test to check this. However it would be better set to 'nil' which is identical to it's curent value, i will do this.

**Comment by paramat** [comment]
Updated.

**Comment by paramat** [comment]
Tested, huger still works.

**Comment by paramat** [comment]
@MoNTE48 are you happy to merge this? I tested it, it doesn't disable hunger.
